### PR TITLE
add core.int128

### PR DESCRIPTION
**Pull request by WalterBright**
This is the opening salvo to support the `cent` type in D. It'll be needed by both the compiler and the generated executables. This version is not optimized, it just establishes a baseline of functionality.

It's built to be used as a standalone package, or have the compiler generate calls to, or have the compiler use it internally to bootstrap cent support.

It's byte endianness independent.

### CODE REVIEW

**Comment by rikkimax** [comment]
Right now this wouldn't work without extra work for people using -betterC due to not being compiled in.

An option might be to specify the signedness via a template parameter, which would allow for both signed and unsigned working and it working in -betterC too.

File: src/core/int128.d [hunk 1]
```diff
@@ -0,0 +1,695 @@
...
+
+nothrow:
+@safe:
+@nogc:
+
+alias I = long;
+alias U = ulong;
+enum Ubits = U.sizeof * 8;
+
+struct Cent
```
Comment (thewilsonator) [inline src/core/int128.d:21]: this is a `ucent`

File: src/core/int128.d [hunk 2]
```diff
@@ -0,0 +1,695 @@
...
+
+/*****************************
+ * Complement
+ * Params:
+ *	c = Cent to complement
+ * Returns:
+ *	complemented value
+ */
+pure
+Cent com(Cent c)
```
Comment (thewilsonator) [inline src/core/int128.d:52]: all these free functions should be operator overloads

File: src/core/int128.d (hunk 1 above)
Comment (WalterBright) [reply src/core/int128.d:21]: ucent is a keyword, cannot use that as a struct name.

Comment (WalterBright) [reply src/core/int128.d:21]: Also, the Cent struct will work with both signed and unsigned operations.

File: src/core/int128.d (hunk 2 above)
Comment (WalterBright) [reply src/core/int128.d:52]: I decided against that because:
1. better to pass arguments by value rather than by ref
2. easier to interface with C, will probably make them extern (C) functions

**Comment by WalterBright** [comment]
> Right now this wouldn't work without extra work for people using -betterC due to not being compiled in.

I know, but have to start somewhere.

> An option might be to specify the signedness via a template parameter, which would allow for both signed and unsigned working and it working in -betterC too.

The underlying signedness depends on which operation is done, just like the CPU. As for templates, I wanted to keep the name mangling out of such low level stuff.

**Comment by rikkimax** [comment]
> > Right now this wouldn't work without extra work for people using -betterC due to not being compiled in.
> 
> I know, but have to start somewhere.

Me an @thewilsonator talked about this on Discord briefly, what we are looking for is more along the lines of my code of: (Boost licensed) https://gist.github.com/rikkimax/a31a3e085f4aeb00ce7206804a9f2a56

But you seem to have something very different in mind. Perhaps you are treating this as compiler hooks rather than a usable type in itself?

**Comment by WalterBright** [comment]
Now, why would adding a new module to druntime, which nobody uses, result in the message:
```
Test 'runnable/sdtor.d' failed. The logged output:
/tmp/dmd/generated/linux/release/32/dmd -conf= -m32 -Irunnable -preview=dtorfields  -fPIC  -odtest_results/runnable -oftest_results/runnable/sdtor_0  runnable/sdtor.d 
runnable/sdtor.d(3872): Error: declaration `(S[2] sb = __error__;)` is not yet implemented in CTFE
```
from the test suite? Are things being pulled that didn't pass?

**Comment by WalterBright** [comment]
@rikkimax I am looking for something designed to be used internally, not so much at user level, hence no operator overloading.

File: src/core/int128.d (hunk 2 above)
Comment (ibuclaw) [reply src/core/int128.d:52]: They don't need to be extern(C), especially with three letter names.

**Comment by Geod24** [comment]
If you want to design it iteratively, which I'm sure you do, put it under `core.internal.int128`, and it will alleviate some of the issue reviews might have, because it's an accepted place to put internal stuff (more hooks are there nowadays).
As long as it doesn't break the build for other people (e.g. other compilers or other archs), then you are free to do whatever you want.

File: src/core/int128.d [hunk 3]
```diff
@@ -0,0 +1,696 @@
...
+ *      shifted value
+ */
+pure
+Cent shl(Cent c, uint n)
+{
+    if (n >= Ubits * 2)
+        return Zero;
+
+    foreach (i; 0 .. n)
+        c = shl1(c);
```
[the remark this answers is not in the document]
Comment (ibuclaw) [reply src/core/int128.d:159]:
```
c.lsl = ((c.lsl << n) | (c.msl >> (Ubits - n - 1) >> 1));
c.msl = c.msl << n;
```
(Untested)

**Review by ibuclaw — CHANGES_REQUESTED** [review]

File: src/core/int128.d (hunk 3 above)
[the remark this answers is not in the document]
Comment (WalterBright) [reply src/core/int128.d:159]: I used a lot of reliance on other functions to get many working. No attempt was made to optimize them. Many of my initiative PRs are currently stalled, which disincentivizes me to spend a lot of effort tuning them. So I went for the baseline implementation.

> (Untested)

I know, it doesn't work :-)

P.S. the unittests I wrote uncovered several embarrassing bugs in it.

File: src/core/int128.d [hunk 4]
```diff
@@ -0,0 +1,696 @@
...
+@nogc:
+
+alias I = long;
+alias U = ulong;
+enum Ubits = U.sizeof * 8;
+
+struct Cent
+{
+    U lsl;      // low 64 bits
+    U msl;      // high 64 bits
```
[the remark this answers is not in the document]
Comment (WalterBright) [reply src/core/int128.d:24]: I know, but then unsigned operations become more complicated and require a cast.

**Comment by WalterBright** [comment]
@Geod24 I view this as not just a compiler thing. It can be used as a building block for many purposes, like the overflow checks in bitop.d. Note that it doesn't import anything, this is deliberate.

**Comment by Geod24** [comment]
@WalterBright : All the more reasons to put it in `core.internal`. It's a lower barrier of entry and doesn't prevent us from moving it to another location later.

You mention that many of your initiative PRs are blocked, but from what I've seen they are always held back on the same disagreement:
- You favor an iterative approach with small PRs;
- Reviewers want to know what is the end goal;

In my opinion, there's two ways to move forward:
1) Put that iterative stuff behind a switch / in an internal module, so it isn't public / it's clear it shouldn't yet be used;
2) Submit a fully finished feature as a single, large PR, and then submit individual chunks as PRs, so one can review both the end goal and the steps, not just the steps;

My understanding is that option 2 doesn't work well for you, hence why I suggest option 1.

Trust me, I **want** to merge your PRs. But for any initiative PR, there is no way for me to tell if it's going in the right direction, I **must** take you on faith, lest I implement it myself to see why you are taking this specific step.

File: src/core/int128.d (hunk 4 above)
[the remark this answers is not in the document]
Comment (ibuclaw) [reply src/core/int128.d:24]: In the most common use cases, this field is either going to be `0` or `-1` anyway, so I see no reason not to streamline that.

File: src/core/int128.d [hunk 5]
```diff
@@ -0,0 +1,696 @@
...
+}
+
+enum One = Cent(1);
+enum Zero = Cent();
```
Comment (ibuclaw) [inline src/core/int128.d:28]: MinusOne is likely going to crop up too (same as CTFloat).

File: src/core/int128.d (hunk 3 above)
[the remark this answers is not in the document]
Comment (ibuclaw) [reply src/core/int128.d:159]: > > (Untested)
> 
> I know, it doesn't work :-)
> 
> P.S. the unittests I wrote uncovered several embarrassing bugs in it.

Ah, yes, because I got the field names the wrong way round, which begs the question, why now just name them `low` and `high` to prevent all confusion.

File: src/core/int128.d (hunk 4 above)
Comment (ibuclaw) [inline src/core/int128.d:24]:
```suggestion
    U low;      // low 64 bits
    U high;     // high 64 bits
```

File: src/core/int128.d [hunk 6]
```diff
@@ -0,0 +1,696 @@
...
+ */
+pure
+Cent shl(Cent c, uint n)
+{
+    if (n >= Ubits * 2)
+        return Zero;
+
+    foreach (i; 0 .. n)
+        c = shl1(c);
+    return c;
```
Comment (ibuclaw) [inline src/core/int128.d:160]:
```suggestion
    if (n >= Ubits * 2)
        return Zero;
    if (n >= Ubits)
    {
        c.msl = c.lsl << (n - Ubits);
        c.lsl = 0;
    }
    else
    {
        c.msl = ((c.msl << n) | (c.lsl >> (Ubits - n - 1) >> 1));
        c.lsl = c.lsl << n;
    }
    return c;
```
Now it's tested. ;-)

File: src/core/int128.d [hunk 7]
```diff
@@ -0,0 +1,696 @@
...
+ */
+pure
+Cent shr(Cent c, uint n)
+{
+    if (n >= Ubits * 2)
+        return Zero;
+
+    foreach (i; 0 .. n)
+        c = shr1(c);
+    return c;
```
Comment (ibuclaw) [inline src/core/int128.d:179]:
```suggestion
    if (n >= Ubits * 2)
        return Zero;
    if (n >= Ubits)
    {
        c.lsl = c.msl >> (n - Ubits);
        c.msl = 0;
    }
    else
    {
        c.lsl = ((c.lsl >> n) | (c.msl << (Ubits - n - 1) << 1));
        c.msl = c.msl >> n;
    }
    return c;
```

**Review by ibuclaw — CHANGES_REQUESTED** [review]

File: src/core/int128.d [hunk 8]
```diff
@@ -0,0 +1,696 @@
...
+ * Unsigned divide c1 / c2.
+ * Params:
+ *      c1 = dividend
+ *      c2 = divisor
+ *      modulus = set to c1 % c2
+ * Returns:
+ *      quotient c1 / c2
+ */
+pure
+Cent udiv(Cent c1, Cent c2, out Cent modulus)
```
Comment (ibuclaw) [inline src/core/int128.d:383]:
```suggestion
/****************************
 * Unsigned divide c1 / c2.
 * Params:
 *      c1 = dividend
 *      c2 = divisor
 * Returns:
 *      quotient c1 / c2
 */
pure
Cent udiv(Cent c1, Cent c2)
{
    Cent modulus;
    return udivmod(c1, c2, modulus);
}

/****************************
 * Unsigned divide c1 / c2. The remainder after the division is stored to modulus.
 * Params:
 *      c1 = dividend
 *      c2 = divisor
 *      modulus = set to c1 % c2
 * Returns:
 *      quotient c1 / c2
 */
pure
Cent udivmod(Cent c1, Cent c2, out Cent modulus)
```

File: src/core/int128.d [hunk 9]
```diff
@@ -0,0 +1,696 @@
...
+ * Signed divide c1 / c2.
+ * Params:
+ *      c1 = dividend
+ *      c2 = divisor
+ *      modulus = c1 % c2
+ * Returns:
+ *      c1 / c2
+ */
+pure
+Cent div(Cent c1, Cent c2, out Cent modulus)
```
Comment (ibuclaw) [inline src/core/int128.d:432]:
```suggestion
/****************************
 * Signed divide c1 / c2.
 * Params:
 *      c1 = dividend
 *      c2 = divisor
 * Returns:
 *      quotient c1 / c2
 */
pure
Cent div(Cent c1, Cent c2)
{
    Cent modulus;
    return divmod(c1, c2, modulus);
}

/****************************
 * Signed divide c1 / c2. The remainder after the division is stored to modulus.
 * Params:
 *      c1 = dividend
 *      c2 = divisor
 *      modulus = set to c1 % c2
 * Returns:
 *      quotient c1 / c2
 */
pure
Cent divmod(Cent c1, Cent c2, out Cent modulus)
```

**Review by ibuclaw — CHANGES_REQUESTED** [review]
Divide operations should be distinguished from Divide/Modulus operations.

**Comment by ibuclaw** [comment]
> Now, why would adding a new module to druntime, which nobody uses, result in the message:
> 
> ```
> Test 'runnable/sdtor.d' failed. The logged output:
> /tmp/dmd/generated/linux/release/32/dmd -conf= -m32 -Irunnable -preview=dtorfields  -fPIC  -odtest_results/runnable -oftest_results/runnable/sdtor_0  runnable/sdtor.d 
> runnable/sdtor.d(3872): Error: declaration `(S[2] sb = __error__;)` is not yet implemented in CTFE
> ```
> 
> from the test suite? Are things being pulled that didn't pass?

You are 58 commits behind dlang/druntime:master.  There's been a bunch of new front-end lowerings to templates added in the meantime, so you need to rebase.

@RazvanN7 are you merging these? Why is there no tests for when druntime implementations are absent (i.e: empty object.d)?

**Comment by RazvanN7** [comment]
@ibuclaw yes, i have been merging some lowerings lately, however, I don't understand what you are referring to? Do you mean betterC tests?

**Comment by ibuclaw** [comment]
> @ibuclaw yes, i have been merging some lowerings lately, however, I don't understand what you are referring to? Do you mean betterC tests?

`__error__` regression is caused by https://github.com/dlang/dmd/pull/13476/

**Comment by RazvanN7** [comment]
Maybe rebasing will fix the issue.

File: src/core/int128.d [hunk 10]
```diff
@@ -0,0 +1,696 @@
...
+
+@trusted
+void print(Cent c)
+{
+    printf("%lld, %lld\n", cast(ulong)c.lsl, cast(ulong)c.msl);
+    printf("x%llx, x%llx\n", cast(ulong)c.lsl, cast(ulong)c.msl);
+}
+}
+
+unittest
```
Comment (ljmf00) [inline src/core/int128.d:607]: This should be `betterC` ready? If so, mark this unittest as `@betterC`.

File: src/core/int128.d [hunk 11]
```diff
@@ -0,0 +1,696 @@
...
+ *      c2 = operand 2
+ * Returns:
+ *      true if c1 == c2
+ */
+pure
+bool eq(Cent c1, Cent c2)
+{
+    //printf("eq %d, %d\n", (c1.msl == c2.msl), (c1.lsl == c2.lsl));
+    //printf("eq (%d, %d) (%d, %d)\n", c1.msl, c1.lsl, c2.msl, c2.lsl);
+    return (c1.msl == c2.msl) && (c1.lsl == c2.lsl);
```
Comment (ljmf00) [inline src/core/int128.d:590]: Why not just `c1 == c2` ? Is the compiler clever enough to generate `PCMPEQQ` instruction, if available? Is this just to avoid calling `opEquals` if an override is available?

File: src/core/int128.d [hunk 12]
```diff
@@ -0,0 +1,696 @@
...
+}
+
+/*******************************************************/
+
+version (unittest)
+{
+import core.stdc.stdio;
+
+@trusted
+void print(Cent c)
```
Comment (ljmf00) [inline src/core/int128.d:600]: Add a version or a compile-time enum variable with a `static if` to avoid unnecessary uncovered lines.

**Review by ljmf00 — CHANGES_REQUESTED** [review]
Please add missing tests to fully cover `gt`, `dec`, `shl`, `shr`, `sar` and `mul`.

**Comment by WalterBright** [comment]
Trying a rebase.

File: src/core/int128.d (hunk 11 above)
Comment (WalterBright) [reply src/core/int128.d]: Why not indeed. You're quite right. Fixed.

File: src/core/int128.d (hunk 10 above)
Comment (WalterBright) [reply src/core/int128.d:591]: betterC doesn't rely on druntime, so is irrelevant here.

File: src/core/int128.d (hunk 12 above)
Comment (WalterBright) [reply src/core/int128.d]: done

File: src/core/int128.d (hunk 8 above)
Comment (WalterBright) [reply src/core/int128.d]: done

File: src/core/int128.d (hunk 4 above)
Comment (WalterBright) [reply src/core/int128.d]: done

**Comment by WalterBright** [comment]
@ibuclaw ready to go

**Review by ljmf00 — APPROVED** [review]

File: src/core/int128.d [hunk 13]
```diff
@@ -0,0 +1,748 @@
...
+ * Negate
+ * Params:
+ *      c = Cent to negate
+ * Returns:
+ *      negated value
+ */
+pure
+Cent neg(Cent c)
+{
+    return inc(com(c)); // ~c + 1
```
Comment (ibuclaw) [inline src/core/int128.d:70]:
```suggestion
    if (c.lo == 0)
        c.hi = -c.hi;
    else
    {
        c.lo = -c.lo;
        c.hi = ~c.hi;
    }
    return c;
```

File: src/core/int128.d [hunk 14]
```diff
@@ -0,0 +1,748 @@
...
+ *      c1 & c2
+ */
+pure
+Cent and(Cent c1, Cent c2)
+{
+    return Cent(c1.lo & c2.lo, c1.hi & c2.hi);
+}
+
+/****************************
+ * Or c1 & c2.
```
Comment (ibuclaw) [inline src/core/int128.d:305]:
```suggestion
 * Or c1 | c2.
```

File: src/core/int128.d [hunk 15]
```diff
@@ -0,0 +1,748 @@
...
+    if (cast(I)c1.hi >= 0)
+    {
+        if (cast(I)c2.hi >= 0)
+            return ugt(c1, c2);
+        return true;
+    }
+    if (cast(I)c2.hi >= 0)
+        return false;
+    return ugt(c1, c2);
+
```
Comment (ibuclaw) [inline src/core/int128.d:579]:
```suggestion
    return (c1.hi == c2.hi) ? (c1.lo > c2.lo) : (cast(I)c1.hi > cast(I)c2.hi);
```

**Review by ibuclaw — CHANGES_REQUESTED** [review]
Having one last sweep through, there's two more easy optimizations/simplifications that can be done to `neg` and `gt` - the latter can be made to be identical to `ugt`, but cast the high part to signed.  Also spotted one documentation typo in `or`.

I'll defer improvements to multiplication, division, rotate, and arithmetic shift for a follow up PR.

Side note, would having `and_not` be useful alongside `and` as a shortcut for the `c1 & ~c2` case?

File: src/core/int128.d [hunk 16]
```diff
@@ -0,0 +1,748 @@
...
+/*****************************
+ * Arithmetic shift right n bits
+ * Params:
+ *      c = Cent to shift
+ *      n = number of bits to shift
+ * Returns:
+ *      shifted value
+ */
+pure
+Cent sar(Cent c, uint n)
```
Comment (ibuclaw) [inline src/core/int128.d:208]: It'd certainly improve usability if all these functions weren't named after x86 mnemonics.  For instance, `lshift`, `rshift`, and `arshift` instead of `shl`, `shr`, and `sar`.  Similarly, the rotate functions could be `lrotate` and `rrotate`, and the signed comparison functions be prefixed with `s` to make it clear that they are signed versions of the unsigned counterparts (eg: `sgt` and `ugt`).

Comment (WalterBright) [reply src/core/int128.d:208]: It doesn't exactly follow the x86 mnemonics, and I've seen those mnemonics more or less used by various CPUs my entire career. They're second nature :-)

I used a `u` prefix for unsigned, and no prefix for signed, to match D's byte/ubyte, short/ushort, cent/ucent, etc. I deliberately did not use the x86 mul/imul, div/idiv mnemonics.

File: src/core/int128.d (hunk 15 above)
Comment (WalterBright) [reply src/core/int128.d:579]: I am all in favor of these improvements. But what would really help is to approve this PR. That way, I can begin incorporating cent support into the compiler, while you can submit PRs for these optimizations. That way, you get the credit for the optimizations, and we can be working in parallel. Currently, not having this PR pulled is a blocker.

Comment (ibuclaw) [reply src/core/int128.d:579]: As noted, I have nothing further to add after these remaining corrections.

File: src/core/int128.d [hunk 17]
```diff
@@ -0,0 +1,748 @@
...
+ * Params:
+ *      c = Cent to test
+ * Returns:
+ *      true if != 0
+ */
+pure
+bool tst(Cent c)
+{
+    return c.hi || c.lo;
+}
```
Comment (ibuclaw) [inline src/core/int128.d:42]: Every single use of this function is `!tst(c)`, so it'd be much better just naming it `bool isZero(Cent c)` and inverting the condition.

File: src/core/int128.d (hunk 16 above)
Comment (ibuclaw) [reply src/core/int128.d:208]: However, this is a public interface and so the naming conventions should really resemble something suitable for use outside of the compiler run-time.

File: src/core/int128.d (hunk 17 above)
Comment (WalterBright) [reply src/core/int128.d:42]: I'm reminded of `isEmpty()` for ranges, and every time I use it I have to stop and think a moment.

File: src/core/int128.d (hunk 16 above)
Comment (WalterBright) [reply src/core/int128.d:208]: byte/ubyte, etc., are a public interface.

**Comment by RazvanN7** [comment]
@WalterBright once you address @ibuclaw 's review, we can get this in. Specifically:

https://github.com/dlang/druntime/pull/3663#discussion_r780712428
https://github.com/dlang/druntime/pull/3663#discussion_r780712803
https://github.com/dlang/druntime/pull/3663#discussion_r780713513

**Comment by ljmf00** [comment]
I would like to vectorize this if this is worth vectorizing.

**Comment by maxhaton** [comment]
> I would like to vectorize this if this is worth vectorizing.

Probably not worth the hassle for now.

File: src/core/int128.d (hunk 17 above)
Comment (WalterBright) [reply src/core/int128.d:42]: True means non-zero and False means zero. Anything that flips that about, like isZero, is inherently confusing to me.

`tst` is not inherently confusing. It's been in wide use for at least 50 years now to mean !=0, probably more, and I've never heard of *anyone* being confused by it. I was a newbie once, too, and don't recall any confusion with it.

I have used inverted logic (`isZero` is inverted logic), and the only reason it is used (NAND gates, NOR gates) is because one less transistor is required. NAND logic is inherently confusing, and hard to get used to. I'd design a circuit using positive logic, and then mechanistically convert it to inverted logic using DeMorgan's Theorem.

File: src/core/int128.d (hunk 15 above)
Comment (WalterBright) [reply src/core/int128.d:579]: The logic I wrote is easier to understand and visually determine to be correct. That's why I prefer it as the baseline implementation. Your version is faster, but is hard to read, and so should go in a followup PR. That way, it the PR breaks things, we know where to look.

File: src/core/int128.d (hunk 14 above)
Comment (WalterBright) [reply src/core/int128.d]: done

File: src/core/int128.d (hunk 13 above)
Comment (WalterBright) [reply src/core/int128.d:70]: I like the simplicity of the first for a baseline implementation. There are a lot of optimizations that can and should be done, but they are all harder to understand. Having a baseline gives something to judge it against.

File: src/core/int128.d (hunk 4 above)
[the remark this answers is not in the document]
Comment (WalterBright) [reply src/core/int128.d]: They should stay unsigned for simplicity. Signed arithmetic is inherently harder, and so should be where the added work is.

**Comment by ibuclaw** [comment]
> > I would like to vectorize this if this is worth vectorizing.
> 
> Probably not worth the hassle for now. 

And even then, the compiler would be able to detect the pattern an do the right thing for all cases except for division. But why vectorize only division? :-)

**Comment by ljmf00** [comment]
> > > I would like to vectorize this if this is worth vectorizing.
> > 
> > 
> > Probably not worth the hassle for now.
> 
> And even then, the compiler would be able to detect the pattern an do the right thing for all cases except for division. But why vectorize only division? :-)

Is DMD able to do it? Yes, I'm talking more about the division, but there are other functions that can be hardly vectorized (multiply and others that rely on big foreach loops, which can't be unrolled) due to the lack of a loop vectorization pass, maybe there is a better approach to dit more directly tho. What I'm trying to say is: for such critical operations, relying on complex compiler optimizations to do some operations can (a) hurt compile-time performance (b) the compiler may not be able to do a good job at all.

There is also a case I'm thinking of, where custom functions could be beneficial to sum 4 cents using 2 `__vector(ulong[2])`. Is the compiler able to figure that out?

Another thing I would like to consider here: currently in C, the alignment of `__int128` is 16, and AFAIK, the default alignment of a struct in D is 8, right? At least appears to be: https://gcc.godbolt.org/z/65Kj5qdTK .

File: src/core/int128.d [hunk 18]
```diff
@@ -0,0 +1,748 @@
...
+
+nothrow:
+@safe:
+@nogc:
+
+alias I = long;
+alias U = ulong;
+enum Ubits = U.sizeof * 8;
+
+struct Cent
```
Comment (ibuclaw) [inline src/core/int128.d:21]:
```suggestion
align(16) struct Cent
```

**Review by ibuclaw — CHANGES_REQUESTED** [review]
At least make this change.

File: src/core/int128.d (hunk 18 above)
Comment (WalterBright) [reply src/core/int128.d]: ok

**Review by ibuclaw — APPROVED** [review]
